### ISSUE TITLE
error to download package from Nuget for a .net8 project 

### ISSUE THREAD

**Issue by RolandoTonin** [Micky5991/EventAggregator#9]
Hy Micky,

I would like to try your eventaggregator service in my .net 8 solution because it is very like to PRISM eventaggregator.
When I try to install 3.0 package I receive an error because it cannot to downgrade Microsoft transitive packages from 9.0 to 8.X
Is it a workaround to yse your package in a .NET 8 solution?

thanks a lot

Rolando

**Comment by Micky5991** [comment]
Hey,

I very recently upgraded every dependency in the EventAggregator to a .NET 9 compatible version. But it looks like my selection of the minimum-version broke certain versions. 

I will create an update with the minimum versions for  `Microsoft.Extensions.*`-packages to be >= 8.x  instead of >= 9.x. 

If you notice any more issues regarding versions, please let me know here.

**Comment by Micky5991** [comment]
I released the update. Please try it again with V3.0.1

https://www.nuget.org/packages/Micky5991.EventAggregator/3.0.1
